//generated by James's shit Python script
#pragma once
#include <cstdint>
struct ActionButtonParam {
    static const wchar_t* name;
    struct data {                                                   
        int8_t regionType;                                       
        int dummyPoly1;                                       
        int dummyPoly2;                                       
        float Radius;                                           
        int Angle;                                            
        float depth;                                            
        float width;                                            
        float height;                                           
        float baseHeightOffset;                                 
        int8_t angleCheckType;                                   
        int AllowAngle;                                       
        int8_t textBoxType;                                      
        int textId;                                           
        int InvalidFlag;                                      
        int grayoutFlag;                                      
        int priority;                                         
        float execInvalidTime;                                  
        int8_t execButtonCircle;                                 
    };
};