//generated by James's shit Python script
#pragma once
#include <cstdint>
struct BehaviorParam_PC {
    int variationId;
    int behaviorJudgeId;
    int8_t ezStateBehaviorType_old;
    int8_t refType;
private:
    short _0xB;
public:
    int refId;
    int sfxVariationId;
    int stamina;
    int mp;
    int8_t category;
    int8_t heroPoint;
    int8_t pad1;
};