//generated by James's shit Python script
#pragma once
#include <cstdint>
struct BonfireWarpParam {
    static const wchar_t* name;
    struct data {                                                   
        int LocationEventId;                                  
        int WarpEventId;                                      
        int BonfireNameId;                                    
        int DescriptionTextId;                                
        int PictureId;                                        
        int8_t ListId;                                           
        int8_t IsDisableQuickwarp;                               
        short CeremonyId;                                       
        int onlineAreaId;                                     
    };
};