//generated by James's shit Python script
#pragma once
#include <cstdint>
struct Ceremony {
    static const wchar_t* name;
    struct data {                                                   
        int EventLayerID;                                     
        int MapStudioLayerID;                                 
        short GparamID_Up;                                      
        short GparamID_Low;                                     
        int PointCloudID;                                     
        int Gl_TextureID;                                     
        int LightGroupID;                                     
        int8_t IsReload;                                         
        int8_t IsDisableOnline;                                  
    };
};