//generated by James's shit Python script
#pragma once
#include <cstdint>
struct ClearCountCorrectParam {
    int MaxHP;
private:
    int _0x4;
public:
    int Unknown1;
    int Unknown2;
private:
    int8_t _0x10;
    int8_t _0x11;
    int8_t _0x12;
    int8_t _0x13;
    int8_t _0x14;
    int8_t _0x15;
    int8_t _0x16;
    int8_t _0x17;
    int8_t _0x18;
    int8_t _0x19;
    int8_t _0x1A;
    int8_t _0x1B;
public:
    int PhysicalATK;
    int MagATK;
    int FireATK;
    int ThunATK;
    int DarkATK;
    int PhysicalDEF;
    int MagDEF;
    int FireDEF;
    int ThunDEF;
    int DarkDEF;
    int Unknown3;
    int Soul;
    int PoisonRES;
    int ToxicRES;
    int BloodRES;
    int CurseRES;
    int FrostRES;
private:
    int _0x60;
public:
    int Unknown4;
};