//generated by James's shit Python script
#pragma once
#include <cstdint>
struct CharaInitParam {
    float BaseRec_mp;
    float BaseRec_sp;
    float red_Falldam;
    int soul;
    int equip_Wep_Right;
    int equip_Subwep_Right;
    int equip_Wep_Left;
    int equip_Subwep_Left;
    int equip_Helm;
    int equip_Armor;
    int equip_Gaunt;
    int equip_Leg;
    int equip_Arrow;
    int equip_Bolt;
    int equip_SubArrow;
    int equip_SubBolt;
    int equip_Accessory1;
    int equip_Accessory2;
    int equip_Accessory3;
    int equip_Accessory4;
    int equip_Accessory5;
    int Equip_Skill_01;
    int Equip_Skill_02;
    int Equip_Skill_03;
    int Equip_Spell_01;
    int Equip_Spell_02;
    int Equip_Spell_03;
    int Equip_Spell_04;
    int Equip_Spell_05;
    int Equip_Spell_06;
    int Equip_Spell_07;
    int Item_01;
    int Item_02;
    int Item_03;
    int Item_04;
    int Item_05;
    int Item_06;
    int Item_07;
    int Item_08;
    int Item_09;
    int Item_10;
    int npcPlayerFaceGenId;
    int npcPlayerThinkId;
    short baseHp;
    short baseMp;
    short baseSp;
    short arrowNum;
    short boltNum;
    short subArrowNum;
    short subBoltNum;
private:
    short _0xBA;
public:
    short QWC_sb;
    short QWC_mw;
private:
public:
    short QWC_cd;
private:
public:
    short soulLvl;
int8_t baseVit;
int8_t baseWil;
int8_t baseEnd;
int8_t baseStr;
int8_t baseDex;
int8_t baseMag;
int8_t baseFai;
int8_t baseLuc;
int8_t baseHeroPoint;
int8_t baseDurability;
int8_t itemNum_01;
int8_t itemNum_02;
int8_t itemNum_03;
int8_t itemNum_04;
int8_t itemNum_05;
int8_t itemNum_06;
int8_t itemNum_07;
int8_t itemNum_08;
int8_t itemNum_09;
int8_t itemNum_10;
int8_t bodyScaleHead;
int8_t bodyScaleBreast;
int8_t BodyScaleAbdomen;
int8_t BodyScaleArm;
int8_t BodyScaleLeg;
int8_t gestureid0;
int8_t gestureid1;
int8_t gestureid2;
int8_t gestureid3;
int8_t gestureid4;
int8_t gestureid5;
int8_t gestureid6;
int8_t npcPlayerType;
int8_t npcPlayerDrawType;
int8_t NpcPlayerSex;
int8_t vowType;
int8_t VoiceType;
private:
    int8_t _0xE7;
public:
    int equip_Wep_Right_GenId;
    int equip_Subwep_Right_GenId;
    int equip_Wep_Left_GenId;
    int equip_Subwep_Left_GenId;
    int equip_Helm_GenId;
    int equip_Gaunt_GenId;
    int equip_Leg_GenId;
    int equip_Wep_Body_GenId;
    int SecondaryItem_01;
    int SecondaryItem_02;
    int SecondaryItem_03;
    int SecondaryItem_04;
    int SecondaryItem_05;
    int SecondaryItem_06;
    int SecondaryItem_07;
    int SecondaryItem_08;
    int8_t secondaryItemNum_01;
    int8_t secondaryItemNum_02;
    int8_t secondaryItemNum_03;
    int8_t secondaryItemNum_04;
    int8_t secondaryItemNum_05;
    int8_t secondaryItemNum_06;
    int8_t secondaryItemNum_07;
    int8_t secondaryItemNum_08;
private:
    short _0x131;
public:
    int8_t EstusFlask;
    int8_t AshenEstusFlask;
};