//generated by James's shit Python script
#pragma once
#include <cstdint>
struct EquipParamAccessory {
    int refId;
    int sfxVariation;
    float weight;
    int behaviorId;
    int basicPrice;
    int sellValue;
    int sortId;
    int qwcId;
    short equipModelId;
    short iconId;
    short shopLv;
    short trophySGradeId;
    short trophySeqId;
    int8_t equipModelCategory;
    int8_t equipModelGender;
    int8_t accessoryCategory;
    int8_t refCategory;
    int8_t spEffectCategory;
private:
    int8_t _0x2F;
    int8_t _0x30;
    int8_t _0x31;
    int8_t _0x32;
    int8_t _0x33;
    int8_t _0x34;
    int8_t _0x35;
    int8_t _0x36;
    int8_t _0x37;
    int8_t _0x38;
    int8_t _0x39;
    int8_t _0x3A;
    int8_t _0x3B;
public:
private:
    bool memBuffer1 : 3;
public:
    bool isDiscard : 1;                                    // bit offset +3
    bool isDrop : 1;                                       // bit offset +4
private:
    int8_t _0x3D;
    int8_t _0x3E;
    int8_t _0x3F;
    int8_t _0x40;
    int8_t _0x41;
    int8_t _0x42;
    int8_t _0x43;
    int8_t _0x44;
    int8_t _0x45;
public:
    int8_t vowType;
private:
    int8_t _0x47;
public:
    int refId1;
    int refId2;
    int refId3;
    int refId4;
private:
public:
    int refId5;
private:
    int8_t _0x4;
    int8_t _0x5;
    int8_t _0x6;
    int8_t _0x7;
    int8_t _0x8;
    int8_t _0x9;
    int8_t _0xA;
    int8_t _0xB;
    int8_t _0xC;
    int8_t _0xD;
    int8_t _0xE;
    int8_t _0xF;
    int8_t _0x10;
    int8_t _0x11;
    int8_t _0x12;
    int8_t _0x13;
    int8_t _0x14;
    int8_t _0x15;
    int8_t _0x16;
    int8_t _0x17;
    int8_t _0x18;
    int8_t _0x19;
    int8_t _0x1A;
    int8_t _0x1B;
    int8_t _0x1C;
    int8_t _0x1D;
    int8_t _0x1E;
    int8_t _0x1F;
    int8_t _0x20;
    int8_t _0x21;
    int8_t _0x22;
    int8_t _0x23;
    int8_t _0x24;
    int8_t _0x25;
    int8_t _0x26;
    int8_t _0x27;
    int8_t _0x28;
    int8_t _0x29;
    int8_t _0x2A;
    int8_t _0x2B;
    int8_t _0x2C;
    int8_t _0x2D;
    int8_t _0x2E;
    int8_t _0x2F;
    int8_t _0x30;
    int8_t _0x31;
    int8_t _0x32;
    int8_t _0x33;
    int8_t _0x34;
    int8_t _0x35;
    int8_t _0x36;
    int8_t _0x37;
    int8_t _0x38;
    int8_t _0x39;
    int8_t _0x3A;
    int8_t _0x3B;
    int8_t _0x3C;
    int8_t _0x3D;
    int8_t _0x3E;
    int8_t _0x3F;
    int8_t _0x40;
    int8_t _0x41;
    int8_t _0x42;
    int8_t _0x43;
    int8_t _0x44;
    int8_t _0x45;
public:
    int8_t Covenant;
};