//generated by James's shit Python script
#pragma once
#include <cstdint>
struct HitEffectSfxParam {
    int Sfx1;
    int Sfx2;
    int Sfx3;
    int Sfx4;
    int Sfx5;
    int Sfx6;
    int Sfx7;
    int Sfx8;
    int Sfx9;
    int Sfx10;
    int Sfx11;
    int Sfx12;
    int Sfx13;
    int Sfx14;
    int Sfx15;
};