//generated by James's shit Python script
#pragma once
#include <cstdint>
struct ItemLotParam {
    int ItemLotId;
    int ItemLotId1;
    int ItemLotId2;
    int ItemLotId3;
    int ItemLotId4;
    int ItemLotId5;
    int ItemLotId6;
    int ItemLotId7;
    int ItemType;
    int ItemType1;
    int ItemType2;
    int ItemType3;
    int ItemType4;
    int ItemType5;
    int ItemType6;
    int ItemType7;
    short DropRateItem;
    short DropRateItem1;
    short DropRateItem2;
    short DropRateItem3;
    short DropRateItem4;
    short DropRateItem5;
    short DropRateItem6;
    short DropRateItem7;
};