//generated by James's shit Python script
#pragma once
#include <cstdint>
struct LockCamParam {
    static const wchar_t* name;
    struct data {                                                   
        float CamDistTarget;                                    
        float RotRange;                                         
        float LockRotXShiftRatio;                               
        float ChrOrgOffsetZ;                                    
        float ChrLockRangeMaxRadius;                            
        float FovYChange;                                       
        float ChrLockRangeMaxRadius_forDark;                    
        float ChrLockRangeMaxRadius_forPitchDark;               
    };
};