//generated by James's shit Python script
#pragma once
#include <cstdint>
struct ReinforceParamWeapon {
    float physicsAtkRate;
    float magicAtkRate;
    float fireAtkRate;
    float thunderAtkRate;
    float staminaAtkRate;
    float saWeaponAtkRate;
    float saDurabilityRate;
    float correctStrengthRate;
    float correctAgilityRate;
    float correctMagicRate;
    float correctFaithRate;
    float physicsGuardCutRate;
    float magicGuardCutRate;
    float fireGuardCutRate;
    float thunderGuardCutRate;
    float poisonGuardResistRate;
    float toxicGuardResistRate;
    float bleedGuardResistRate;
    float curseGuardResistRate;
    float staminaGuardResistRate;
    int8_t spEffectId1;
    int8_t spEffectId2;
    int8_t spEffectId3;
    int8_t ResidentSpEffectId1;
    int8_t ResidentSpEffectId2;
    int8_t ResidentSpEffectId3;
    int8_t materialSetId;
    int8_t materialSetId;
    float darkAtkRate;
    float darkCutRate;
    float StabilityAtkRate;
    float StabilityCutRate;
    float frostGuardResistRate;
};