//generated by James's shit Python script
#pragma once
#include <cstdint>
struct RoleParam {
    int8_t teamType;
private:
    int8_t _0x1;
    int8_t _0x2;
    int8_t _0x3;
public:
    int phantomParamId;
    int spEffectId;
    int spEffectId1;
    int spEffectId2;
    int spEffectId3;
    int spEffectId4;
    int spEffectId5;
    int spEffectId6;
    int spEffectId7;
    int spEffectId8;
    int spEffectId9;
    int soapstoneColor1;
    int soapstoneColor;
    int animEntry;
    int itemLotId;
    int8_t voiceChat;
    int8_t displayNameType;
private:
    short _0x43;
public:
    int displayTeamTypeName;
    int teamType1;
    int phantomParamId1;
    int phantomParamId2;
    int phantomParamId3;
    int spEffectId10;
    int spEffectId11;
    int spEffectId12;
    int spEffectId13;
};