//generated by James's shit Python script
#pragma once
#include <cstdint>
struct SpEffectVfxParam {
    int midstSfxID;
    int midstSeID;
    int initSfxID;
    int InitSeID;
    int FinishSfxID;
    int FinishSeID;
    float camouflageBeginDist;
    float camouflageEndDist;
    int transformProtectorID;
    short midstDmyID;
    short initDmyID;
    short FinishDmyID;
    int8_t EffectType;
    int8_t SoulParamIDForWepEnchant;
private:
public:
    int8_t soulParamIdForWepEnchant0;
    int8_t PlayCategory;
    int8_t PlayPriority;
    bool ExistEffectForLarge : 1;                          // bit offset +0
    bool ExistEffectForSoul : 1;                           // bit offset +1
    bool EffectInvisibleAtCamouflage : 1;                  // bit offset +2
    bool useCamouflage : 1;                                // bit offset +3
    bool InvisibleAtFriendCamouflage : 1;                  // bit offset +4
    bool addMapAreaBlock : 1;                              // bit offset +5
    bool halfCamouflage : 1;                               // bit offset +6
    bool isFullBodyTransformProtectorID : 1;               // bit offset +7
    bool :0;
    bool IsInvisibleWeapon : 1;                            // bit offset +0
    bool IsSilence : 1;                                    // bit offset +1
    bool isGauntletProtectorId : 1;                        // bit offset +2
    bool Unk1 : 1;                                         // bit offset +3
    bool Unk2 : 1;                                         // bit offset +4
    bool Unk3 : 1;                                         // bit offset +5
    bool Unk4 : 1;                                         // bit offset +6
    bool Unk5 : 1;                                         // bit offset +7
    int DecalId0;
    int DecalId1;
    int8_t soulParamIdForWepEnchant1;
    int8_t SpEffectSp0;
    int8_t SpEffectSp1;
    int8_t bodyProtectorType;
    int SpSfxId0;
    int SpSfxId1;
    int SpSfxId2;
    int SpSfxId3;
    int SpSfxId4;
    int SpSfxId5;
    int SpSfxId6;
    int SpSfxId7;
    int SpSfxId8;
    int SpSfxId9;
    int SpSfxId10;
    int SpSfxId11;
    int SpSfxId12;
    int SpSfxId13;
    int SpSfxId14;
    int SpSfxId15;
    int8_t Unk6;
    int8_t PhantomType;
    int8_t CamouflageGhost;
    int8_t Unk7;
    int PhantomParamId;
    float EmissiveIntensityScale;
    float Unk8;
    short BodyProtectorVal;
    short Unk9;
    float CinderIntensityScale;
};