//generated by James's shit Python script
#pragma once
#include <cstdint>
struct ThrowParam {
    static const wchar_t* name;
    struct data {                                                   
        int AtkChrId;                                         
        int DefChrId;                                         
        float Dist;                                             
        float DiffAngMin;                                       
        float DiffAngMax;                                       
        float UpperYRange;                                      
        float LowerYRange;                                      
        float DiffAngMyToDef;                                   
        int ThrowTypeId;                                      
        int AtkAnimId;                                        
        int DefAnimId;                                        
        short EscHp;                                            
        short SelfEscCycleTime;                                 
        short SphereCastRadiusRateTop;                          
        short SphereCastRadiusRateLow;                          
        int8_t PadType;                                          
        int8_t AtkEnableState;                                   
        int8_t AtkSorbDmyId;                                     
        int8_t DefSorbDmyId;                                     
        int8_t ThrowType;                                        
        int8_t SelfEscCycleCnt;                                  
        int8_t DmyHasChrDirType;                                 
    };
};