//
// Created by ojgpr on 2021-11-06.
//

#pragma once
#include "Params/ActionButtonParam.h"
#include "Params/AiSoundParam.h"
#include "Params/AtkParam_Npc.h"
#include "Params/AtkParam_Pc.h"
#include "Params/AttackElementCorrectParam.h"
#include "Params/BehaviourParam_PC.h"
#include "Params/BonfireWarpParam.h"
#include "Params/Bullet.h"
#include "Params/CalcCorrectGraph.h"
#include "Params/Ceremony.h"
#include "Params/CharaInitParam.h"
#include "Params/ClearCountCorrectParam.h"
#include "Params/DecalParam.h"
#include "Params/EquipMtrlSetParam.h"
#include "Params/EquipParamAccessory.h"
#include "Params/EquipParamGoods.h"
#include "Params/EquipParamProtector.h"
#include "Params/EquipParamWeapon.h"
#include "Params/HitEffectSfxParam.h"
#include "Params/ItemLotParam.h"
#include "Params/LockCamParam.h"
#include "Params/LodParam.h"
#include "Params/Magic.h"
#include "Params/MapMimicryEstablishmentParam.h"
#include "Params/NpcParam.h"
#include "Params/ObjActParam.h"
#include "Params/ObjectParam.h"
#include "Params/PhantomParam.h"
#include "Params/PlayRegionParam.h"
#include "Params/ReinforceParamWeapon.h"
#include "Params/RoleParam.h"
#include "Params/ShopLineupParam.h"
#include "Params/SpEffectParam.h"
#include "Params/SpEffectVfxParam.h"
#include "Params/SwordArtsParam.h"
#include "Params/ThrowParam.h"
#include "Params/UpperArmParam.h"
#include "Params/WetAspectParam.h"